Repository Workiva/flowgraph, pull requests merged in 2019-04, with the labels that each got.

#1 Initial Commit to OpenSource Repository
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  LICENSE
  Makefile
  NOTICE
  README.md
  aviary.yaml
  docs/complex-1.png
  docs/complex-2.png
  docs/trivial.png
  documentation/css/default.css
  documentation/css/highlight.css
  documentation/flowgraph.core.html
  documentation/flowgraph.edge.html
  documentation/flowgraph.error.html
  documentation/flowgraph.flowgraph.html
  documentation/flowgraph.html
  documentation/flowgraph.protocols.html
  documentation/flowgraph.queue.html
  documentation/flowgraph.signal.html
  documentation/flowgraph.thread-control.html
  documentation/flowgraph.utils.html
  documentation/flowgraph.vertex.html
  documentation/index.html
  documentation/js/highlight.min.js
  documentation/js/jquery.min.js
  documentation/js/page_effects.js
  project.clj
  src/flowgraph.clj
  src/flowgraph/core.clj
  src/flowgraph/edge.clj
  src/flowgraph/error.clj
  src/flowgraph/flowgraph.clj
  src/flowgraph/protocols.clj
  src/flowgraph/queue.clj
  src/flowgraph/signal.clj
  src/flowgraph/thread_control.clj
  src/flowgraph/utils.clj
  src/flowgraph/vertex.clj
  test/flowgraph/graph_test.clj
  test/flowgraph/revoke_test.clj
  workivabuild.Dockerfile
Labels: InfoSec Review Required, Merge Requirements Unmet, RM Ready

#2 EVA-983 - Add CircleCI to flowgraph
  .circleci/clojars/profiles.clj
  .circleci/config.yml
  .circleci/scripts/update-tocs.sh
  .circleci/scripts/verify-dockerfile.sh
  .circleci/scripts/verify-docs.sh
  .circleci/scripts/verify-license-headers.sh
  .gitattributes
  .gitignore
  Makefile
  README.md
  documentation/css/default.css
  documentation/css/highlight.css
  documentation/flowgraph.core.html
  documentation/flowgraph.edge.html
  documentation/flowgraph.error.html
  documentation/flowgraph.flowgraph.html
  documentation/flowgraph.html
  documentation/flowgraph.protocols.html
  documentation/flowgraph.queue.html
  documentation/flowgraph.signal.html
  documentation/flowgraph.thread-control.html
  documentation/flowgraph.utils.html
  documentation/flowgraph.vertex.html
  documentation/highlight/highlight.min.js
  documentation/highlight/solarized-light.css
  documentation/index.html
  documentation/js/page_effects.js
  package.json
  project.clj
Labels: Merge Requirements Met, RM Ready

#4 Recide 1.0.0 -> 1.0.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#6 RM-48838 Release flowgraph v0.1.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#7 Threads created get named after graph name
  src/flowgraph/core.clj
Labels: Merge Requirements Met
